In [1]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.12.0


In [2]:
print(tf.config.list_physical_devices('GPU'))

[]


In [1]:
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import os
import cv2
os.chdir("../")
%pwd

'c:\\Users\\Public\\Documents\\Project\\Kidney-Diseases-Classification'

In [15]:
model = load_model(os.path.join("artifacts","training", "model.h5"))

import numpy as np
import os
from pathlib import Path

# Prompt the user to enter the image file path
image_path = Path("C:/Users/Public/Documents/Project/Kidney-Diseases-Classification/artifacts/data_ingestion/dataset/val/Cyst/Cyst- (328).jpg")

# Check if the specified file exists
if os.path.exists(image_path):
    # Load and process the image
    test_image = cv2.imread(str(image_path))
    test_image = cv2.resize(test_image, (224, 224))
    test_image = test_image / 255.0
    test_image = np.array(test_image)
    
    test_image = np.expand_dims(test_image, axis=0)
    
    
    
    

    # Assuming `model` is already defined
    result = np.argmax(model.predict(test_image), axis=1)
    
    print("Predicted class index:", result)
else:
    print("The specified image file does not exist.")

if result[0] == 0:
    prediction = 'Cyst'
    print("Cyst")
elif result[0] == 1:
    prediction = 'Normal'
    print("normal")
elif result[0] == 2:
    prediction = 'Stone'
    print("Stone")
else:
    prediction = 'Tumor'
    print("Tumor")


1/1 [==============================] - 1s 763ms/step
Predicted class index: [0]
Cyst


In [35]:
pip install opencv-python

  Obtaining dependency information for opencv-python from https://files.pythonhosted.org/packages/38/d2/3e8c13ffc37ca5ebc6f382b242b44acb43eb489042e1728407ac3904e72f/opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
   ---------------------------------------- 0.1/38.1 MB 1.3 MB/s eta 0:00:29
   ---------------------------------------- 0.3/38.1 MB 2.6 MB/s eta 0:00:15
    --------------------------------------- 0.6/38.1 MB 3.8 MB/s eta 0:00:10
   - -------------------------------------- 1.0/38.1 MB 4.9 MB/s eta 0:00:08
   - -------------------------------------- 1.2/38.1 MB 4.5 MB/s eta 0:00:09
   - -------------------------------------- 1.4/38.1 MB 4.4 MB/s eta 0:00:09
   - -------------------------------------- 1.4/38.1 MB 4.5 MB/s eta 0:00:09
   - -------------------------------------- 1.4/38.1 MB 4.5 MB/s eta 0:00:09
   - ------------------

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
import cv2
import os
import glob
import matplotlib.pyplot as plt
model = load_model(os.path.join("artifacts","training", "model.h5"))
from sklearn.preprocessing import MinMaxScaler

In [9]:
import cv2
import glob
import os
import numpy as np
from sklearn.preprocessing import MinMaxScaler

test_images = []
test_labels = []

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

for dir_path in glob.glob("./artifacts/data_ingestion/dataset/test/*"):
    label = dir_path.split("\\")[-1]
    print(label)
    for img_path in glob.glob(os.path.join(dir_path, "*.jpg")):
        print(img_path)
        img = cv2.imread(img_path)
        img = cv2.resize(img, (224, 224))

        # Apply rescaling (normalization)
        img = img / 255.0  # Assuming the original range was [0, 255]
        
        test_images.append(img)
        test_labels.append(label)

# Convert the lists to NumPy arrays
test_images = np.array(test_images)
test_labels = np.array(test_labels)

# Reshape and flatten the images


Cyst
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1004).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1012).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1042).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1081).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1083).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1092).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1098).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1100).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1104).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1136).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1142).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (117).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1176).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1181).jpg
./artifacts/data_ingestion/dataset/test\Cyst\Cyst- (1192).jpg
./artif

In [10]:
test_images

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 

In [11]:
from sklearn import preprocessing
lab = preprocessing.LabelEncoder()
lab.fit(test_labels)
test_lab_en = lab.transform(test_labels)
test_lab_en

array([0, 0, 0, ..., 3, 3, 3])

In [12]:
result=model.predict(test_images)

40/40 [==============================] - 24s 589ms/step


In [10]:
result

array([[9.9958760e-01, 1.8159312e-07, 4.1191012e-04, 2.5774145e-07],
       [4.7062829e-01, 2.0331247e-03, 5.2731198e-01, 2.6604726e-05],
       [5.4984766e-01, 1.0767008e-02, 4.3886346e-01, 5.2193168e-04],
       ...,
       [1.3297267e-04, 9.7938752e-01, 8.3031673e-03, 1.2176255e-02],
       [5.8220704e-03, 5.7398981e-01, 3.6209010e-02, 3.8397908e-01],
       [8.9072366e-04, 5.4112989e-02, 3.3176609e-03, 9.4167864e-01]],
      dtype=float32)

In [11]:
y_pred = np.argmax(result, axis = 1)
y_pred


array([0, 2, 0, ..., 1, 1, 3], dtype=int64)

In [12]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(test_lab_en, y_pred)
cm

array([[361,   4,   5,   2],
       [  1, 503,   4,   1],
       [  4,   7, 128,   0],
       [  0,  16,   2, 211]], dtype=int64)

In [13]:
from sklearn.metrics import classification_report

report = classification_report(test_lab_en, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.99      0.97      0.98       372
           1       0.95      0.99      0.97       509
           2       0.92      0.92      0.92       139
           3       0.99      0.92      0.95       229

    accuracy                           0.96      1249
   macro avg       0.96      0.95      0.96      1249
weighted avg       0.96      0.96      0.96      1249

